baseURL = "https://armoghan-blogs.netlify.app/"
canonifyURLs=true
pluralizeListTitles = false
summaryLength   = 25

languageCode  = "en-us"
title         = "Armoghan"

[params]
    description     = "My Tech Blogs"
    contactEmail    = "Armoghan@proton.me"
    googleAnalytics = "G-X28GYK9J5J"      # Google Analytics v4
    adsense         = "pub-2047325115998150"
    math            = false   # best to enable this in the front matter of a page
    mermaid         = false   # best to enable this in the front matter of a page

    # Social Media Params
    facebook   = "https://www.facebook.com/armoghanul.mohmin"
    twitter    = "https://twitter.com/Armoghan12"
    youtube    = ""
    instagram  = "https://www.instagram.com/___armoghan/"
    github     = "https://github.com/Armoghan-ul-Mohmin"
    linkedin   = "http://www.linkedin.com/in/armoghan-ul-mohmin-4289a9248"


# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 3
    [[menu.main]]
        name = "Cheat Sheets"
        url = "/cheatsheets/"
        weight = 4
    [[menu.main]]
        name = "Author"
        url = "https://armoghan-ul-mohmin.github.io/Portfolio/"
        weight = 5
    [[menu.main]]
        name = "Contact"
        url = "https://armoghan-ul-mohmin.github.io/Portfolio/Contact.html"
        weight = 6

[markup.goldmark.parser.attribute]
    block = true

# Don't touch this
[markup.goldmark.renderer]
    unsafe = true
    
[module]
  [module.hugoVersion]
    extended = true
    min = "0.91.2"